sudo: false
language: node_js
node_js:
  - "6"
  - "8"

before_install:
  - travis_retry npm install
  - travis_retry npm install typescript

script:
  - npm test
  - tsc --version ; tsc -p test

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
